### ISSUE TITLE
Foundational Work

### ISSUE THREAD

**Issue by FronzoMimlet** [FronzoMimlet/SSTAT#13]
### Overview
Experiment with the tools chosen to build some foundational environment to begin development on

### Intended Outcome
- [ ] Build a view that can handle 3D elements
- [ ] Implement rudimentary controls onto this view
- [ ] https://github.com/FronzoMimlet/SSTAT/issues/6

**Comment by FronzoMimlet** [comment]
New branch created
